### ISSUE TITLE
TEMPLATE_NAME/logo.png - is this an intentional placeholder

### ISSUE THREAD

**Issue by shoulders** [joomdev/jd_seattle#4]
in the jd-seattle-default.json and jd-seattle-solid-header.json there are 'TEMPLATE_NAME/logo.png' insteaded of '"tpl_jdseattle/logo.png"'

from https://www.joomdev.com/products/templates/jd-seattle-template

````json
   "defult_logo": "TEMPLATE_NAME/logo.png",
   "mobile_logo": "TEMPLATE_NAME/logo2x.png",
   "enable_sticky_menu": "1",
   "stickey_horizontal_menu_mode": "right",
   "stickey_header_logo": "TEMPLATE_NAME/logo_sticky.png",
   "stickey_block_1_type": "blank",
   "stickey_block_1_position": "",
   "stickey_block_1_custom": "",
   "stickey_header_logo": "TEMPLATE_NAME/logo_sticky.png",
````

these are mine when i have updated them

````
    "defult_logo": "common/mbm-logo-250.jpg",
    "mobile_logo": "common/mbm-logo-250.jpg",
````

**Comment by chetanmadaan** [comment]
Hi Jon,

This is the default for astroid for creating the template layout JSOn on first start.

TEMPLATE_NAME is replace by the real template name here:
https://github.com/joomdev/Astroid-Framework/blob/master/astroid/astroid-framework/framework/helper.php#L512

**Comment by shoulders** [comment]
thanks for the update
