### ISSUE TITLE
JD Process - Does not have a home

### ISSUE THREAD

**Issue by shoulders** [joomdev/jd_seattle#9]
This extension that exists in the quickstart package and the JDSeattle extensions archive does not have a home at github or on your site (not that I have found).

Can you give it a proper home, Joomdev page and/or a github repo

![image](https://user-images.githubusercontent.com/319997/66051251-7d95d480-e526-11e9-8a25-d13ea59d19bf.png)

**Comment by chandanndeep** [comment]
Duplicate https://github.com/joomdev/jd_seattle/issues/8
